name: $(Build.DefinitionName)_$(Date:yyyy-MM-dd)_v$(Rev:rr)

trigger: 
  batch: true
  branches:
   include:
   - main
  
  paths:
    include:
      - '*'
    exclude:
      - SPN-Terraform-Deployment
      - tf-destroy-pipelines.yml
      
variables:
- name: systm.debug
  value: 'true'
- group: 'service-connection'
- group: 'ssh-keys'
- name: RG_Name
  value: "rg-ADO-2"            # Can be passed via `-backend-config=`"resource_group_name=<resource group name>"` in the `init` command.
- name: StorageAccName
  value: "mystorageacct16425"  # Can be passed via `-backend-config=`"storage_account_name=<storage account name>"` in the `init` command.
- name: ContainerName
  value: "storage-container"         # Can be passed via `-backend-config=`"container_name=<container name>"` in the `init` command.
- name: BlobName
  value: "hub-spoke-peering"         # Can be passed via `-backend-config=`"key=<blob key name>"` in the `init` command.
- name: ADO-Environment
  value: "PROD"
- name: tf_planFile
  value: "main.tfplan$(Rev:rr)"  
  
  # Reusing pipeline in multiple directories
stages:
- template: templates/azure_pipeline_template.yml
  parameters:
    SourceDirectory: '$(System.DefaultWorkingDirectory)/infrastrucure/network'   # change directory to network
    infrastructure: 'Network'
- template: templates/azure_pipeline_template.yml
  parameters:
    SourceDirectory: '$(System.DefaultWorkingDirectory)/infrastrucure/compute'   # change directory to compute
    infrastructure: 'Compute'

#- template: templates/azure_pipeline_template.yml
#  parameters:
#    SourceDirectory: '$(System.DefaultWorkingDirectory)/infrastrucure/routes'    # change directory to routes 
     #infrastructure: 'Routes'
 
