name: $(Build.DefinitionName)_$(Date:yyyy-MM-dd)_v$(Rev:rr)

trigger: none
  #batch: true
  #branches:
    #include:
    #- main
  
 # paths:
 #   include:
 #     - '*'
 #   exclude:
  #    - SPN-Terraform-Deployment

variables:
- group: 'service-connection'
- name: RG_Name
  value: "terraform-backend"            # Can be passed via `-backend-config=`"resource_group_name=<resource group name>"` in the `init` command.
- name: StorageAccName
  value: "terraformstates16555"  # Can be passed via `-backend-config=`"storage_account_name=<storage account name>"` in the `init` command.
- name: ContainerName
  value: "remote-backend"         # Can be passed via `-backend-config=`"container_name=<container name>"` in the `init` command.
- name: BlobName
  value: "spn-ado-1"                   # Can be passed via `-backend-config=`"key=<blob key name>"` in the `init` command.
- name: ADO-Environment
  value: "PROD"

# Reusing pipeline in multiple directories
stages:
- template: templates/azure_pipeline_template.yml
  parameters:
    SourceDirectory: 'infrastrucure/network'   # change directory to network

#- template: templates/azure_pipeline_template.yml
#  parameters:
#    SourceDirectory: 'infrastrucure/compute'   # change directory to compute

#- template: templates/azure_pipeline_template.yml
#  parameters:
#    SourceDirectory: 'infrastrucure/routes'    # change directory to routes 

