name: $(Build.DefinitionName)_$(Date:yyyy-MM-dd)_v$(Rev:rr)

trigger: none
  
variables:
- name: systm.debug
  value: 'true'
- group: 'service-connection'
- name: RG_Name
  value: "rg-ADO-2"            # Can be passed via `-backend-config=`"resource_group_name=<resource group name>"` in the `init` command.
- name: StorageAccName
  value: "mystorageacct16425"  # Can be passed via `-backend-config=`"storage_account_name=<storage account name>"` in the `init` command.
- name: ContainerName
  value: "storage-container"         # Can be passed via `-backend-config=`"container_name=<container name>"` in the `init` command.
- name: BlobName
  value: "hub-spoke-peering"         # Can be passed via `-backend-config=`"key=<blob key name>"` in the `init` command.
- name: ADO-Environment
  value: "PROD"
- name: projectName
  value: "hub and spokes vnet peering"
- name: definitionID
  value: "10"
- name: buildID
  value: "108"
  
  # Reusing pipeline in multiple directories
jobs:
- template: templates/destroy_template.yml
  parameters:
    infrastructure: 'Network'
    tfplan: 'network.tflan'

- template: templates/destroy_template.yml
  parameters:
    infrastructure: 'Compute'
    tfplan: 'compute.tflan'

- template: templates/destroy_template.yml
  parameters:
    infrastructure: 'Routes'
    tfplan: 'routes.tflan'
 