name: $(Build.DefinitionName)_$(Date:yyyy-MM-dd)_v$(Rev:rr)

trigger:
  batch: true
  branches:
    include:
    - main
  
  paths:
    include:
      - '*'
    exclude:
      - SPN-Terraform-Deployment

# Reusing template pipeline for multiple directories
stages:
- template: templates/destroy_pipeline_template.yml
  parameters:
    SourceDirectory: 'infrastrucure/network'   # change directory to network

- template: templates/destroy_pipeline_template.yml
  parameters:
    SourceDirectory: 'infrastrucure/compute'   # change directory to compute

- template: templates/destroy_pipeline_template.yml
  parameters:
    SourceDirectory: 'infrastrucure/routes'    # chang directory to routes 
