# Pipeline template to be used in the main pipeline for multiple stages

stages:
- stage: Build_${{parameters.infrastructure}}
  displayName: '${{parameters.SourceDirectory}} Build Stage'
  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: validate
    steps:
    - checkout: self
    - template: terraform_install.yml

    - script: terraform version
      displayName: 'terraform version'

    - bash: |
        terraform init -input=false \
          -backend-config="resource_group_name=$(RG_Name)" \
          -backend-config="storage_account_name=$(StorageAccName)" \
          -backend-config="container_name=$(ContainerName)" \
          -backend-config="key=$(BlobName)"
        terraform fmt && terraform validate
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
      displayName: 'terraform fmt and validate'
      workingDirectory: ${{parameters.SourceDirectory}}

  - job: plan_and_publish
    dependsOn: validate
    condition: succeeded()
    steps:
    - checkout: self
    - bash: | 
        terraform init -upgrade
        terraform plan '-out=$(tf_planFile)' '-lock=false'
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
        TF_VAR_hub-sshkey: $(hub-sshkey)
        TF_VAR_hub-sshkey-pub: $(hub-sshkey-pub)
        TF_VAR_sp1-sshkey: $(sp1-sshkey)
        TF_VAR_sp1-sshkey-pub: $(sp1-sshkey-pub)
        TF_VAR_sp2-sshkey: $(sp2-sshkey)
        TF_VAR_sp2-sshkey-pub: $(sp2-sshkey-pub)
        TF_VAR_mypublic-ip: $(mypublic-ip)
      workingDirectory: ${{parameters.SourceDirectory}}
      displayName: 'terraform plan'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)' 
        artifact: $(tf_planFile) # artifactName
        publishLocation: 'pipeline' # upload artifact to pipeline
      displayName: 'Publishing artifact'
    continueOnError: false  
   
- stage: Deploy_${{parameters.infrastructure}}
  displayName: '${{parameters.SourceDirectory}} Deploy Stage'
  pool:
    vmImage: ubuntu-latest

  jobs:
  - deployment: apply
    environment: $(ADO-Environment)        
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(tf_planFile)
            displayName: 'Downloading artifact'

          - template: terraform_install.yml  
          
          - bash: |
              chmod a+x $(tf_planFile)
              terraform apply $(tf_planFile) '-auto-approve -lock=true' 
            workingDirectory: '$(Pipeline.Workspace)'
            env:
              ARM_CLIENT_ID: $(SPN2-client-id)
              ARM_TENANT_ID: $(SPN2-tenant-id)
              ARM_CLIENT_SECRET: $(SPN2-client-secret)
              ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
            displayName: 'terraform apply'


