# Pipeline template to be used in the main pipeline for multiple stages
#
pool:
  vmImage: ubuntu-latest

stages:
- stage: Build_${{parameters.SourceDirectory}}
  displayName: '${{parameters.SourceDirectory}} Build Stage'
  jobs:
  - job: validate
    steps:
    - checkout: self
    - template: terraform_install.yml

    - script: terraform version
      displayName: 'terraform version'

    - bash: |
        terraform init -input=false \
          -backend-config="resource_group_name=$(RG_Name)" \
          -backend-config="storage_account_name=$(StorageAccName)" \
          -backend-config="container_name=$(ContainerName)" \
          -backend-config="key=$(BlobName)"
        terraform fmt && terraform validate
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
      displayName: 'terraform fmt and validate'
      workingDirectory: ${{parameters.SourceDirectory}}

  - job: plan
    dependsOn: validate
    condition: succeeded()
    steps:
    - checkout: self
    - bash: |
        terraform plan -out=main.tfplan -lock=false
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
        TF_VAR_hub-sshkey: 
        TF_VAR_hub-sshkey-pub:
        TF_VAR_sp1-sshkey:
        TF_VAR_sp1-sshkey-pub:
        TF_VAR_sp2-sshkey:
        TF_VAR_sp2-sshkey-pub:
      workingDirectory: ${{parameters.SourceDirectory}}
      displayName: 'terraform plan'
    continueOnError: false  

- stage: Deploy_${{parameters.SourceDirectory}}
  displayName: '${{parameters.SourceDirectory}} Deploy Stage'
  jobs:
  - deployment: apply
    environment: $(ADO-Environment)        
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - bash: terraform apply main.tfplan -auto-approve -lock=true 
            env:
              ARM_CLIENT_ID: $(SPN2-client-id)
              ARM_TENANT_ID: $(SPN2-tenant-id)
              ARM_CLIENT_SECRET: $(SPN2-client-secret)
              ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
            workingDirectory: ${{parameters.SourceDirectory}}
            displayName: 'terraform apply'


