# Pipeline template to be used in the main pipeline for multiple stages

variables:
- group: 'service-connection'
- name: RG_Name
  value: "terraform-backend"            # Can be passed via `-backend-config=`"resource_group_name=<resource group name>"` in the `init` command.
- name: StorageAccName
  value: "terraformstates16555"  # Can be passed via `-backend-config=`"storage_account_name=<storage account name>"` in the `init` command.
- name: ContainerName
  value: "remote-backend"         # Can be passed via `-backend-config=`"container_name=<container name>"` in the `init` command.
- name: BlobName
  value: "spn-ado-1"                   # Can be passed via `-backend-config=`"key=<blob key name>"` in the `init` command.
- name: ADO-Environment
  value: "PROD"

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build_${{parameters.SourceDirectory}}
  displayName: '${{parameters.SourceDirectory}} Build Stage'
  jobs:
  - job: validate
    steps:
    - checkout: self
    - template: templates/terraform_install.yml

    - script: terraform version
      displayName: 'terraform version'

    - bash: |
        terraform init -input=false \
          -backend-config="resource_group_name=$(RG_Name)" \
          -backend-config="storage_account_name=$(StorageAccName)" \
          -backend-config="container_name=$(ContainerName)" \
          -backend-config="key=$(BlobName)"
        terraform fmt && terraform validate
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      displayName: 'terraform fmt and validate'
      workingDirectory: ${{parameters.SourceDirectory}}

  - job: plan
    dependsOn: validate
    condition: succeeded()
    steps:
    - checkout: self
    - bash: |
        terraform plan -out=main.tfplan -lock=false
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      workingDirectory: ${{parameters.SourceDirectory}}
      displayName: 'terraform plan'
    continueOnError: false  

- stage: Deploy_${{parameters.SourceDirectory}}
  displayName: '${{parameters.SourceDirectory}} Deploy Stage'
  jobs:
  - deployment: apply
    environment: $(ADO-Environment)        
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - bash: terraform apply main.tfplan -auto-approve -lock=true 
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            workingDirectory: ${{parameters.SourceDirectory}}
            displayName: 'terraform apply'


