# Pipeline template to be used in the main pipeline for multiple stages

stages:
- stage: Plan-Destroy-${{parameters.infrastructure}}
  displayName: '${{parameters.SourceDirectory}} Plan Stage'
  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: validate

    steps:
    - checkout: self
    - template: terraform_install.yml

    - script: terraform version
      displayName: 'terraform version'

    - bash: |
        terraform init -input=false \
          -backend-config="resource_group_name=$(RG_Name)" \
          -backend-config="storage_account_name=$(StorageAccName)" \
          -backend-config="container_name=$(ContainerName)" \
          -backend-config="key=$(BlobName)"
        terraform fmt && terraform validate
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
      displayName: 'terraform fmt and validate'
      workingDirectory: ${{parameters.SourceDirectory}}

  - job: plan-destroy-publish
    dependsOn: validate
    condition: succeeded()
    steps:
    - checkout: self
    - bash: |
        terraform init -upgrade
        terraform plan -destroy -out=$(tf_destroyFile) -lock=false
      env:
        ARM_CLIENT_ID: $(SPN2-client-id)
        ARM_TENANT_ID: $(SPN2-tenant-id)
        ARM_CLIENT_SECRET: $(SPN2-client-secret)
        ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
      workingDirectory: ${{parameters.SourceDirectory}}
      displayName: 'terraform plan destroy'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)' 
        artifact: $(tf_destroyFile) # artifactName
        publishLocation: 'pipeline' # upload artifact to pipeline
    continueOnError: false  

- stage: Apply-Destroy-${{parameters.infrastructure}}
  displayName: '${{parameters.SourceDirectory}} Apply Stage'
  pool:
    vmImage: ubuntu-latest

  jobs:
  - deployment: apply-destroy
    environment: $(ADO-Environment)        
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(tf_destroyFile)
            displayName: 'Downloading artifact'

          - template: terraform_install.yml  
          
          - bash: |
              chmod a+x $(tf_destroyFile)
              terraform apply $(tf_destroyFile) -auto-approve -lock=true
            workingDirectory: '$(Pipeline.Workspace)'
            env:
              ARM_CLIENT_ID: $(SPN2-client-id)
              ARM_TENANT_ID: $(SPN2-tenant-id)
              ARM_CLIENT_SECRET: $(SPN2-client-secret)
              ARM_SUBSCRIPTION_ID: $(SPN2-subscription-id)
            displayName: 'terraform destroy'
