# Pipeline template to be used in the main pipeline for multiple stages

pool:
  vmImage: ubuntu-latest

stages:
- stage: Plan_Destroy_${{parameters.SourceDirectory}}
  displayName: '${{parameters.SourceDirectory}} Plan Stage'
  jobs:
  - job: validate
    steps:
    - checkout: self
    - template: terraform_install.yml

    - script: terraform version
      displayName: 'terraform version'

    - bash: |
        terraform init -input=false \
          -backend-config="resource_group_name=$(RG_Name)" \
          -backend-config="storage_account_name=$(StorageAccName)" \
          -backend-config="container_name=$(ContainerName)" \
          -backend-config="key=$(BlobName)"
        terraform fmt && terraform validate
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      displayName: 'terraform fmt and validate'
      workingDirectory: ${{parameters.SourceDirectory}}

  - job: plan-destroy
    dependsOn: validate
    condition: succeeded()
    steps:
    - checkout: self
    - bash: |
        terraform plan -destroy -out=main.destroy.tfplan -lock=false
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      workingDirectory: ${{parameters.SourceDirectory}}
      displayName: 'terraform plan destroy'
    continueOnError: false  

- stage: Apply_Destroy_${{parameters.SourceDirectory}}
  displayName: '${{parameters.SourceDirectory}} Apply Stage'
  jobs:
  - deployment: apply-destroy
    environment: $(ADO-Environment)        
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - bash: terraform apply main.destroy.tfplan -auto-approve -lock=true 
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            workingDirectory: ${{parameters.SourceDirectory}}
            displayName: 'terraform destroy'
